### ISSUE TITLE
Definir o que sera aplicado na versao 0.1

### ISSUE THREAD

**Issue by jakeliny** [dev-house-community/Loki-Feeder#1]

**Comment by caio-emidio** [comment]
Pelo o que estavamos conversando. 
Sensor de quantidade de racao sobrando e liberacao de racao de tempos em tempos.

**Comment by jakeliny** [comment]
- Sensor ultrasonico na tampa do pote para definir quanto está acabando a ração
- Sistema de liberação de ração em porções para o pote principal com intervalo de tempo definido
- Envio de dados para uma API 
    - Quantidade de comida no pote
    - Tempo e horario que irá liberar a próxima porção
    - Tempo estimado para acabar a ração no pote

**Comment by DevRadhy** [comment]
Abrir para possibilidade de encaixe de medidores de ração, por exemplo, ter a possibilidade de por um medidor de 70g de ração, ou 100g liberando a quantidade respectiva para o pet.

**Comment by caio-emidio** [comment]
Esse sensor que vc ta falando... eh como se fosse uma balanca no pote? ou eh o q @DevRadhy ?
Pq liberar a quantidade respectiva teoricamente ja faz parte do sistema de liberacao de racao.
O ponto que estavamos discutindo na issue #6 eh pq gatos nao comem comida velha. Entao temos q pensar em uma solucao q seja boa pra eles.

**Comment by caio-emidio** [comment]
> * Sensor ultrasonico na tampa do pote para definir quanto está acabando a ração
> * Sistema de liberação de ração em porções para o pote principal com intervalo de tempo definido
> * Envio de dados para uma API
>   
>   * Quantidade de comida no pote
>   * Tempo e horario que irá liberar a próxima porção
>   * Tempo estimado para acabar a ração no pote

Podemos fechar com essa parte entao?

**Comment by jakeliny** [comment]
Sim, podemos fechar com essas funcionalidades

**Comment by jakeliny** [comment]
Sim, podemos fechar a 0.1 nessas funcionalidades
